Replace Settings + Better Animated Armory Support
Synthesis-Collective/speedandreachfixes pull request #3
Opened 2021-08-29 23:15 UTC by radj307

- using latest synthesis version
- replaced if-else statement block with a priority-based system that is configurable through the settings menu / json

2021-09-03 23:01 UTC, Noggog requested changes
Awesome stuff!  Much better and more flexible system overall.  Put out some thoughts/issue comments around on a few things

2021-09-03 23:01 UTC, Noggog commented on SpeedandReachFixes/ModKeywords/NWTA.cs
> +    public static class NWTA // New Weapon Types and Animations
I think you designed these by hand?  Just so you know for any future work, there's tooling to make these files automatically
https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys#create-your-own-mappings
Much easier if there's tons of them

It's a bit hard to get at, currently, as you have to build it yourself, but eventually I hope to add the logic into Synthesis for easy access.

2021-09-03 23:01 UTC, Noggog commented on SpeedandReachFixes/Program.cs
> +                        attack.AttackData!.StrikeAngle += 7;
I think I prefer the old setup without the Linq `Where` usage.  Mainly because it lets the compiler null error logic work better, and avoids the need to use the null forgiveness operator `!`.  I generally have used less Linq lately as it's not able to trickle down the information of what it checked/filtered out too well (yet, maybe they'll improve the compiler in the future).

2021-09-03 23:01 UTC, Noggog commented on SpeedandReachFixes/Program.cs
> +                    state.PatchMod.Weapons.Remove(weap);
This is dangerous in a subtle way.   Just because we didn't end up making changes to a specific record in this patcher doesn't mean we want to remove it from the patch, as the record might have existed within the patch with changes from a previous patcher.  By removing it, we're nuking the changes a previous patcher might've done.

I have thought about offering an alternative mode where the patch object is always "fresh" and has no records even if previous patchers ran before, but it would require the Merge logic to be finished.   If that was finished up and enabled, then this remove logic would be safe, as it would only affect the current patcher.  But as of now, the patch mod object contains changes from previous patchers, so it's not good to remove from, generally.

As an alternative, people generally follow the DeepCopy pattern:
- Do some initial checking and short circuit if somethings not right, like the `weap.Data` call is doing
- Do a `var weapon = weap.DeepCopy()` call, which is like a `GetOrAddAsOverride`, but doesn't add it to the patch yet
- Only after all the works/checks have been done and we're sure we made some changes and want to have them in the outgoing patch, you can do a `state.PatchMod.Weapons.Set(weapon);` to put the modified copy in as the record to export
This lets us control the ITPOs while avoiding the need to call a Remove

2021-09-03 23:01 UTC, Noggog commented on SpeedandReachFixes/Settings.cs
> +    /**
Love the comments!   In C# it's generally written as:
```cs
/// <summary>
/// Contains default value constants used internally.
/// </summary>
```

Just for reference, comments on a function might look like:
```cs
/// <summary>
/// blah blah
/// </summary>
/// <param name="current">blah blah</param>
/// <param name="local">blah blah</param>
/// <param name="changed">blah blah</param>
/// <returns>blah blah</returns>
```

If written this way, they'll show up in intellisense tooltips and such

A quick way to get comments started is just write `///` at the top of a function/class and most IDEs will fill out the `summary>` tags.  And at that point, new lining inside the comments should suggest things like `<param>` and the other stuff

2021-09-03 23:01 UTC, Noggog commented on SpeedandReachFixes/Settings.cs
> +        [MaintainOrder] [SettingName("[EXPERIMENTAL] Change Swing Angle for all races.")] [Tooltip("Don't change this unless you know what you're doing!")] public bool WeaponSwingAngleChanges = false
I feel like this is a bit much for one line?  Not a big deal either way

2021-09-03 23:01 UTC, Noggog commented on SpeedandReachFixes/Settings.cs
> +        [SettingName("Modifier")] [Tooltip("When checked, adds the specified values rather than overwriting them. Negative values will subtract.")] public bool IsModifier;
Hmm, maybe a name like `Additive` or something would be clearer on first glance?   I'd personally have to check the tooltip to know what the setting would be doing as is.

2021-09-03 23:01 UTC, Noggog commented on SpeedandReachFixes/Settings.cs
> +            changed = !local.Equals(current) && !local.Equals(Constants.NullFloat);
Might not need to, but there's a EqualsWithin alternative that will check equality within an acceptable variance.  Helps with the imprecise equality of floats that might just be 0.0000001 different

2021-09-03 23:01 UTC, Noggog commented on SpeedandReachFixes/Settings.cs
> +            return changed ? IsModifier ? current + local : local : current;
I had to do a double take on the double Conditional operator, haha.
I think this is correct logic, but might be good to split into some if statements to help readability

2021-09-03 23:01 UTC, Noggog commented on SpeedandReachFixes/Settings.cs
> +                var priority = stats.GetPriority(weapon.EditorID!, weapon.Keywords);
Use of the null forgiveness operator here might throw if EDID on a weapon is missing.  Probably rare, but there's always some weirdo out there.  
Can probably either:
- Take in a `string?` in the `GetPriority` function, and check `id.IsNullOrWhitespace` to catch either
- Swap to a TryGetHighestPriority that returns false if EDID is null, or somesuch
- keep the null forgiveness operator, but make sure to check and skip weapons without an EditorID earlier in the logic chain.

Edit:  Actually, probably just remove, as it's not used?

2021-09-03 23:01 UTC, Noggog commented on SpeedandReachFixes/Settings.cs
> +    public class WeaponStats
Love it.  Flexible keyword inputs, and the priority concepts help a lot!  Awesome stuff.

2021-09-03 23:01 UTC, Noggog commented on SpeedandReachFixes/Settings.cs
> +        [MaintainOrder] [Tooltip("The keyword attached to this weapon type.")] public FormLink<IKeywordGetter>? Keyword;
Dont think making this nullable is doing much but making you need to check for null in the code.

More likely, we can make it non nullable `FormLink<IKeywordGetter>` and check `Keyword.IsNull` which will check not if the object itself is null, but if the FormKey points to all zeros (eg a FormID that is 000000)

2021-09-03 23:01 UTC, Noggog commented on SpeedandReachFixes/Settings.cs
> +        public bool IsNull()
With the above `Keyword` definition improvement, we can maybe rename this to `ShouldSkip`

2021-09-04 13:08 UTC, radj307 commented on SpeedandReachFixes/Settings.cs
> +    /**
Yeah, sorry about the comment syntax, I'm coming from using Doxygen for everything which barely supports C# anyway lol
I'm liking the autofill for XML documentation!

2021-09-04 13:28 UTC, radj307 commented on SpeedandReachFixes/Settings.cs
> +            return changed ? IsModifier ? current + local : local : current;
Moved the outer layer of ternary expression to an if statement, added some parenthesis & comments to make it more readable

2021-09-04 14:04 UTC, radj307 commented on SpeedandReachFixes/ModKeywords/NWTA.cs
> +    public static class NWTA // New Weapon Types and Animations
Replaced all of the manual keywords with the autogenerated ones
(this is much easier lol)

2021-09-04 14:13 UTC, radj307 commented on SpeedandReachFixes/Program.cs
> +                        attack.AttackData!.StrikeAngle += 7;
Thanks for the feedback! Swapped the linq statements out for the null check

2021-09-04 14:17 UTC, radj307 commented on SpeedandReachFixes/Settings.cs
> +                var priority = stats.GetPriority(weapon.EditorID!, weapon.Keywords);
Yeah, It was a leftover from my earlier implementation where you could define multiple categories for the same keyword (intentionally), and by using the priority system combined with a list of words that appear in the editor ID have finer control over which weapons were placed where.

Decided to scrap it as I felt increasing memory usage for a feature almost no one would use was too much

2021-09-04 14:40 UTC, radj307 commented on SpeedandReachFixes/Settings.cs
> +        [MaintainOrder] [Tooltip("The keyword attached to this weapon type.")] public FormLink<IKeywordGetter>? Keyword;
Replaced nullable Keyword member with SetToNull() & IsNull checks

2021-09-04 15:01 UTC, radj307 commented on SpeedandReachFixes/Program.cs
> +                    state.PatchMod.Weapons.Remove(weap);
Thanks for the info! Implemented in commit 47806ee

2021-09-04 15:02 UTC, radj307 commented on SpeedandReachFixes/ModKeywords/NWTA.cs
> +    public static class NWTA // New Weapon Types and Animations
267a0e1

2021-09-04 15:02 UTC, radj307 commented on SpeedandReachFixes/Program.cs
> +                        attack.AttackData!.StrikeAngle += 7;
f1d500a

2021-09-04 15:04 UTC, radj307 commented on SpeedandReachFixes/Settings.cs
> +            return changed ? IsModifier ? current + local : local : current;
300ffa1

2021-09-04 15:05 UTC, radj307 commented on SpeedandReachFixes/Settings.cs
> +                var priority = stats.GetPriority(weapon.EditorID!, weapon.Keywords);
300ffa1

2021-09-04 15:06 UTC, radj307 commented on SpeedandReachFixes/Settings.cs
> +            changed = !local.Equals(current) && !local.Equals(Constants.NullFloat);
300ffa1

2021-09-04 15:07 UTC, radj307 reviewed
Also replaced float.Equals calls with float.EqualsWithin
Using default epsilon value for now

2021-09-04 15:16 UTC, radj307 commented on SpeedandReachFixes/Settings.cs
> +        public bool IsNull()
Changed in 3e8ab6c

2021-09-04 15:17 UTC, radj307 commented on SpeedandReachFixes/Settings.cs
> +    /**
3e8ab6c

2021-09-04 15:19 UTC, radj307 commented on SpeedandReachFixes/Settings.cs
> +        [MaintainOrder] [Tooltip("The keyword attached to this weapon type.")] public FormLink<IKeywordGetter>? Keyword;
1fb53bb

2021-09-04 16:06 UTC, radj307 commented
I made a lot of changes in commit 7834588, after some testing it appears using:
`state.PatchMod.GameSettings.Add(...)` works correctly when modifying game settings.

Is this better or worse for performance, and are there potential problems with this approach?

2021-09-07 00:06 UTC, Noggog reviewed
Looking great!  Thanks for all the hard work!  I think maybe just address the ITPO is the only blocking comment above.  The rest is just minor null checking simplifications that could be made

2021-09-07 00:06 UTC, Noggog commented on SpeedandReachFixes/Program.cs
> +				foreach ( IRaceGetter? race in state.LoadOrder.PriorityOrder.Race().WinningOverrides() ) { // iterate through all races that have the ActorTypeNPC keyword.
What inspired you to do the "Improved null checking for race" commit related to this area?  `WinningOverrides` should only ever return `IRaceGetter` (no null), so assigning it to `IRaceGetter?` and then doing the null checks that then requires downstream seems unnecessary?

If WinningOverrides is giving you a null, then that's a bug I'd want to fix in Mutagen

2021-09-07 00:06 UTC, Noggog commented on SpeedandReachFixes/Program.cs
> +					foreach ( var attack in state.PatchMod.Races.GetOrAddAsOverride( race ).Attacks ) {
This has the potential to make some make some ITPOs.   Probably good to do the DeepCopy pattern, or add an additional `continue` check that weeds out any race that has no attacks with any attack data.

2021-09-07 00:06 UTC, Noggog commented on SpeedandReachFixes/Settings.cs
> +			if ( weapon == null )
Doesn't need to be checked.  The parameter given is `Weapon`, not `Weapon?`, so it should never be null by the time it gets to this function call

2021-09-07 00:06 UTC, Noggog commented on SpeedandReachFixes/Settings.cs
> +            if ( stats?.ShouldSkip() != false )
this can probably just be `if (stats.ShouldSkip())`

`GetHighestPriorityStats` is returning `WeaponStats` which can't be null (as opposed to if it had returned `WeaponStats?`), so we don't need to check.

2021-09-07 00:06 UTC, Noggog commented on SpeedandReachFixes/Settings.cs
> +		public List<WeaponStats> WeaponStats { get; set; } = new() {
I'm starting to think it would be good to generally follow the C# IDE formatting for Synthesis Collective projects?

I'm totally in understanding that people from all corners of the coding world are coming to contribute, and have very different mental style rules engrained from the languages they typically code in.  So for most projects I look at, I never ever make mention of styling/naming conventions that aren't C#, as it's just not that important.

But I think in the case of Synthesis Collective projects it makes a bit more sense to encourage an agreed style.  I think as people come and go working on these projects, if everyone flip/flops the code to their style they're used to from their main language, then the codebases will change drastically depending on the last person that modified them, which will make it harder to digest what changes occurred in the past as the diffs will have so much unimportant style preference changes happening.  

I think the VS/Rider formatting rules are at least one constant everyone will be able to use to get things consistent so there's not that style flip/flop spam as authors come and go?  I dont know that I'll enforce every project within the collective HAS to have the IDE C# style strictly to be added, but I think people putting in extra work to move the styling away from the typical C# style is harmful/wasteful, as it will eventually be snapped back the second someone else comes and runs a formatter.

Anyway, just thinking out loud. mainly.  We can talk about this more on the discord, if you want.   I may or may not write up something to this effect in the Synthesis Collective wiki area and start encouraging it more.

2021-09-07 01:01 UTC, radj307 commented on SpeedandReachFixes/Settings.cs
> +		public List<WeaponStats> WeaponStats { get; set; } = new() {
Sorry about that, I reset my formatting settings to prevent this in the future.

2021-09-07 01:21 UTC, Noggog commented on SpeedandReachFixes/Program.cs
> +                    var raceCopy = race.DeepCopy();
Will need a `state.PatchMod.Races.Set(raceCopy)` call to match

2021-09-07 01:31 UTC, merged